# Generated by Django 5.0.1 on 2026-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
