# Generated by Django 6.0.6 on 2026-09-10 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyDigitalTwin',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('domain_scores', models.JSONField(default=dict)),
                ('skill_evidence', models.JSONField(default=dict)),
                ('learning_history', models.JSONField(default=list)),
                ('error_patterns', models.JSONField(default=dict)),
                ('overall_competency_score', models.FloatField(default=0.0)),
                ('learning_debt_score', models.FloatField(default=0.0)),
                ('promotion_readiness_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sih_competency_twins',
            },
        ),
        migrations.CreateModel(
            name='CompetencyDomain',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sih_competency_domains',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OfficerRole',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('required_competency_levels', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'sih_officer_roles',
            },
        ),
        migrations.CreateModel(
            name='CompetencySkill',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.IntegerField(choices=[(1, 'Awareness'), (2, 'Working'), (3, 'Practitioner'), (4, 'Expert')], default=2)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='sih.competencydomain')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_skills', to='sih.competencyskill')),
            ],
            options={
                'db_table': 'sih_competency_skills',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(blank=True, max_length=300)),
                ('option_d', models.CharField(blank=True, max_length=300)),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(default=2)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_questions', to='sih.competencydomain')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_questions', to='sih.competencyskill')),
            ],
            options={
                'db_table': 'sih_diagnostic_questions',
            },
        ),
        migrations.CreateModel(
            name='IGOTCourse',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('igot_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('provider', models.CharField(default='iGOT Karmayogi', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_hours', models.FloatField(default=2.0)),
                ('url', models.URLField(blank=True)),
                ('level', models.CharField(default='Beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('domains_covered', models.ManyToManyField(blank=True, related_name='igot_courses', to='sih.competencydomain')),
                ('skills_covered', models.ManyToManyField(blank=True, related_name='igot_courses', to='sih.competencyskill')),
            ],
            options={
                'db_table': 'sih_igot_courses',
            },
        ),
        migrations.CreateModel(
            name='LearningDebtItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('gap_score', models.FloatField()),
                ('impact_score', models.FloatField()),
                ('debt_score', models.FloatField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_cause_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_debts', to='sih.competencyskill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sih.competencyskill')),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_items', to='sih.competencydigitaltwin')),
            ],
            options={
                'db_table': 'sih_learning_debt_items',
                'ordering': ['-debt_score'],
            },
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('current_assignment', models.CharField(blank=True, max_length=200)),
                ('career_goal', models.CharField(blank=True, max_length=200)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='sih.officerrole')),
            ],
            options={
                'db_table': 'sih_officer_profiles',
            },
        ),
        migrations.CreateModel(
            name='LearningPathway',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('pathway_steps', models.JSONField(default=list)),
                ('total_hours', models.FloatField(default=0.0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('addresses_debt', models.ManyToManyField(blank=True, to='sih.learningdebtitem')),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways', to='sih.competencydigitaltwin')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_pathways', to='sih.officerprofile')),
            ],
            options={
                'db_table': 'sih_learning_pathways',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('domain_scores', models.JSONField(default=dict)),
                ('overall_score', models.FloatField(default=0.0)),
                ('responses', models.JSONField(default=list)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to='sih.officerprofile')),
            ],
            options={
                'db_table': 'sih_diagnostic_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='competencydigitaltwin',
            name='officer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='competency_twin', to='sih.officerprofile'),
        ),
        migrations.CreateModel(
            name='CareerCompetencyRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('verified_competencies', models.JSONField(default=dict)),
                ('gaps_closed', models.JSONField(default=list)),
                ('training_completed', models.JSONField(default=list)),
                ('assessment_history', models.JSONField(default=list)),
                ('promotion_readiness', models.FloatField(default=0.0)),
                ('next_role_ready', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_record', to='sih.officerprofile')),
            ],
            options={
                'db_table': 'sih_career_records',
            },
        ),
        migrations.CreateModel(
            name='TPACProgram',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('program_code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.IntegerField(default=3)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(default='Online', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('domains_covered', models.ManyToManyField(blank=True, related_name='tpac_programs', to='sih.competencydomain')),
                ('skills_covered', models.ManyToManyField(blank=True, related_name='tpac_programs', to='sih.competencyskill')),
            ],
            options={
                'db_table': 'sih_tpac_programs',
            },
        ),
    ]
