# Generated by Django 5.0.1 on 2026-09-05 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerDigitalTwin',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('verified_mastery', models.JSONField(default=dict)),
                ('self_reported_mastery', models.JSONField(default=dict)),
                ('confidence_gap', models.JSONField(default=dict)),
                ('learning_debt_score', models.FloatField(default=0.0)),
                ('failure_risk_score', models.FloatField(default=0.0)),
                ('concept_drift_score', models.FloatField(default=0.0)),
                ('career_goal', models.CharField(blank=True, default='', max_length=200)),
                ('target_exam_score', models.FloatField(default=75.0)),
                ('verified_skills', models.JSONField(default=dict)),
                ('retention_scores', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_digital_twins',
            },
        ),
        migrations.CreateModel(
            name='AgentDecisionLog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(choices=[('analytics', 'Analytics Agent'), ('evaluator', 'Evaluator Agent'), ('planner', 'Planner Agent'), ('content', 'Content Agent'), ('tutor', 'Tutor Agent'), ('mentor', 'Mentor Agent')], max_length=20)),
                ('trigger', models.CharField(blank=True, max_length=100)),
                ('input_state', models.JSONField(default=dict)),
                ('decision', models.TextField()),
                ('output', models.JSONField(default=dict)),
                ('verified', models.BooleanField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to=settings.AUTH_USER_MODEL)),
                ('twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='nexus_core.learnerdigitaltwin')),
            ],
            options={
                'db_table': 'nexus_agent_decision_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
