# Generated by Django 5.0.1 on 2026-01-13 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weak_topics', models.JSONField(default=list, help_text='List of weak topics with scores')),
                ('strong_topics', models.JSONField(default=list, help_text='List of strong topics with scores')),
                ('predicted_weak_topics', models.JSONField(default=list, help_text='ML predicted weak topics')),
                ('mindset', models.CharField(default='neutral', max_length=20)),
                ('learning_strategy', models.JSONField(default=dict, help_text='Personalized learning recommendations')),
                ('performance_trend', models.JSONField(default=list, help_text='Historical performance data')),
                ('avg_study_time', models.FloatField(default=0.0, help_text='Average study time in minutes')),
                ('consistency_score', models.FloatField(default=0.0, help_text='Consistency score (0-100)')),
                ('engagement_level', models.CharField(default='neutral', max_length=20)),
                ('mastered_subtopics', models.JSONField(default=list)),
                ('recommended_learning_path', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
                'db_table': 'analytics',
                'ordering': ['-updated_at'],
            },
        ),
    ]
