# Generated by Django 5.0.1 on 2026-02-05 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
