# Generated by Django 5.2.6 on 2026-01-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0007_remove_proctoringreport_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('face_not_visible', 'Face Not Visible'), ('multiple_faces', 'Multiple Faces Detected'), ('looking_away', 'Looking Away'), ('speech_detected', 'Speech Detected'), ('screen_sharing', 'Screen Sharing Detected'), ('browser_resize', 'Browser Resized'), ('full_screen_exit', 'Exited Full Screen')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='proctoring_evidence/')),
                ('severity_score', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='quiz.quizsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
