# Generated by Django 5.0.1 on 2026-09-05 09:09

import django.db.models.deletion
import syllabus.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(blank=True, default='', max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('end_exam_date', models.DateField(blank=True, null=True)),
                ('target_percentage', models.IntegerField(default=75)),
                ('available_hours_per_day', models.FloatField(default=2.0)),
                ('overall_verified_mastery', models.FloatField(default=0.0)),
                ('overall_self_mastery', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_academic_subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusUpload',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=syllabus.models.syllabus_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_extracted_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='syllabus.academicsubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_syllabus_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusRoadmap',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('roadmap_json', models.JSONField(default=dict)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('total_units', models.IntegerField(default=0)),
                ('total_topics', models.IntegerField(default=0)),
                ('total_subtopics', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='syllabus.academicsubject')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='syllabus.syllabusupload')),
            ],
            options={
                'db_table': 'nexus_syllabus_roadmaps',
            },
        ),
    ]
