# Generated by Django 5.0.1 on 2026-01-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoringreport',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_report', to='quiz.quizsession'),
        ),
        migrations.AddField(
            model_name='proctoringevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='quiz.quizsession'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='response',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.quizsession'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='prerequisite_subtopics',
            field=models.ManyToManyField(blank=True, related_name='dependent_subtopics', to='quiz.subtopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='quiz.topic'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics',
            field=models.ManyToManyField(related_name='quizzes', to='quiz.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.topic'),
        ),
        migrations.AddIndex(
            model_name='proctoringreport',
            index=models.Index(fields=['is_flagged'], name='quiz_procto_is_flag_e70a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringreport',
            index=models.Index(fields=['-integrity_score'], name='quiz_procto_integri_857635_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['session', '-timestamp'], name='quiz_procto_session_46b0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['event_type'], name='quiz_procto_event_t_2ad45a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subtopic',
            unique_together={('topic', 'name')},
        ),
    ]
