# Generated by Django 5.0.1 on 2026-02-10 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '__first__'),
        ('quiz', '0017_alter_aigeneratedquestion_id_alter_question_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='prerequisite_module',
            field=models.ForeignKey(blank=True, help_text='Student must complete this module before taking the quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_assignments', to='learning.learningmodule'),
        ),
    ]
