# Generated by Django 5.0.1 on 2026-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quizassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
