# Generated by Django 5.0.1 on 2026-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_question_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text="AI's self-reported confidence (0.0-1.0)", null=True),
        ),
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='suggested_difficulty',
            field=models.IntegerField(blank=True, help_text="AI's suggested difficulty level (1-5)", null=True),
        ),
    ]
