# Generated by Django 5.2.6 on 2026-02-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_remove_question_auto_grade_remove_question_max_words_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='ai_feedback',
        ),
        migrations.RemoveField(
            model_name='response',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='response',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='response',
            name='grading_status',
        ),
        migrations.RemoveField(
            model_name='response',
            name='keyword_matches',
        ),
        migrations.RemoveField(
            model_name='response',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='response',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='response',
            name='similarity_score',
        ),
        migrations.RemoveField(
            model_name='response',
            name='teacher_feedback',
        ),
        migrations.RemoveField(
            model_name='response',
            name='teacher_score',
        ),
        migrations.RemoveField(
            model_name='response',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='word_count',
        ),
    ]
