# Generated by Django 5.2.6 on 2026-02-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_response_keyword_matches_response_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='auto_grade',
            field=models.BooleanField(default=False, help_text='Whether to enable AI auto-grading'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_words',
            field=models.IntegerField(blank=True, help_text='Maximum word count', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_words',
            field=models.IntegerField(blank=True, help_text='Minimum word count', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, help_text='Model answer for grading reference'),
        ),
        migrations.AddField(
            model_name='question',
            name='required_keywords',
            field=models.JSONField(blank=True, help_text='Keywords that must be present', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mcq', help_text='Type of question', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('mixed', 'Mixed / All Types'), ('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mixed', help_text='Type of questions in this quiz', max_length=20),
        ),
    ]
