# Generated by Django 5.0.1 on 2026-01-13 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_paste', 'Copy/Paste Detected'), ('screenshot', 'Screenshot Attempt'), ('fullscreen_exit', 'Exited Fullscreen'), ('suspicious_activity', 'Suspicious Activity'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional event data')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_events', models.IntegerField(default=0)),
                ('high_severity_events', models.IntegerField(default=0)),
                ('integrity_score', models.FloatField(default=100.0, help_text='0-100, lower is worse')),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], default=3)),
                ('irt_difficulty', models.FloatField(default=0.0, help_text='IRT difficulty parameter (b)')),
                ('irt_discrimination', models.FloatField(default=1.0, help_text='IRT discrimination parameter (a)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the correct answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_asked', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.IntegerField(default=10)),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in minutes', null=True)),
                ('is_adaptive', models.BooleanField(default=True, help_text='Enable adaptive difficulty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_question_index', models.IntegerField(default=0)),
                ('current_difficulty_level', models.IntegerField(default=3)),
                ('student_ability', models.FloatField(default=0.0, help_text='IRT ability estimate (theta)')),
                ('total_score', models.FloatField(default=0.0)),
                ('behavior_score', models.FloatField(default=0.0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('total_tab_switches', models.IntegerField(default=0)),
                ('total_hesitations', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0, help_text='Average response time in seconds')),
                ('detected_mindset', models.CharField(choices=[('confident', 'Confident'), ('confused', 'Confused'), ('stressed', 'Stressed'), ('disengaged', 'Disengaged'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
            ],
            options={
                'db_table': 'quiz_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField(help_text='Time taken to answer in seconds')),
                ('hesitation_count', models.IntegerField(default=0, help_text='Number of times answer was changed')),
                ('tab_switches', models.IntegerField(default=0, help_text='Number of tab switches during this question')),
                ('confidence_level', models.FloatField(default=0.5, help_text='Calculated confidence (0-1)')),
                ('question_difficulty_at_time', models.IntegerField(help_text='Difficulty level when question was presented')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'responses',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subtopics',
                'ordering': ['topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['name'],
            },
        ),
    ]
