# Generated by Django 5.2.6 on 2026-01-14 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_image_alter_question_subtopic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_retakes',
            field=models.BooleanField(default=False, help_text='Allow students to retake this quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Maximum number of attempts allowed'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_answers',
            field=models.BooleanField(default=False, help_text='Show correct answers after completion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_explanations',
            field=models.BooleanField(default=True, help_text='Show explanations for answers'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='attempt_number',
            field=models.IntegerField(default=1, help_text='Attempt number for this quiz'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='hidden_from_parent',
            field=models.BooleanField(default=False, help_text='Hide this session from parent view'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
