# Generated by Django 5.2.6 on 2026-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_allow_retakes_quiz_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this quiz active'),
        ),
    ]
