# Generated by Django 5.2.6 on 2026-01-16 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_proctoringreport_reviewed_by_and_more'),
        ('users', '0008_classroomleaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='users.classroom')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quiz.quiz')),
            ],
            options={
                'db_table': 'quiz_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('quiz', 'classroom')},
            },
        ),
    ]
