# Generated by Django 5.2.6 on 2026-02-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_question_learning_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='auto_grade',
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_words',
        ),
        migrations.RemoveField(
            model_name='question',
            name='min_words',
        ),
        migrations.RemoveField(
            model_name='question',
            name='model_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='required_keywords',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice')], default='mcq', help_text='Type of question', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('mixed', 'Mixed / All Types'), ('mcq', 'Multiple Choice')], default='mixed', help_text='Type of questions in this quiz', max_length=20),
        ),
    ]
