# Generated by Django 5.2.6 on 2026-02-12 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_response_ai_score_response_final_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='keyword_matches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='teacher_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
