# Generated by Django 5.2.6 on 2026-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoringevent',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('face_not_visible', 'Face Not Visible'), ('multiple_faces', 'Multiple Faces Detected'), ('looking_away', 'Looking Away'), ('speech_detected', 'Speech Detected'), ('screen_sharing', 'Screen Sharing Detected'), ('browser_resize', 'Browser Resized'), ('full_screen_exit', 'Exited Full Screen'), ('auto_submit', 'Auto Submission Triggered')], max_length=50),
        ),
    ]
