# Generated by Django 5.0.1 on 2026-09-05 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluator_agent', '0001_initial'),
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDebt',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('root_concept', models.CharField(max_length=200)),
                ('debt_score', models.FloatField(default=0.0)),
                ('affected_topics', models.JSONField(default=list)),
                ('persistence_days', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_topic_mastery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_as_root', to='evaluator_agent.topicmastery')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_debts', to='syllabus.academicsubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_learning_debts',
                'ordering': ['-debt_score'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('plan_json', models.JSONField(default=list)),
                ('total_duration_min', models.IntegerField(default=0)),
                ('exam_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger', models.CharField(default='manual', max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='syllabus.academicsubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_study_plans',
                'ordering': ['-generated_at'],
            },
        ),
    ]
