# Generated by Django 5.2.6 on 2026-01-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsession',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
