# Generated by Django 5.2.6 on 2026-01-15 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quizsession_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proctoringreport',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='proctoringreport',
            name='session',
        ),
        migrations.DeleteModel(
            name='ProctoringEvent',
        ),
        migrations.DeleteModel(
            name='ProctoringReport',
        ),
    ]
