# Generated by Django 5.2.6 on 2026-01-17 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quizassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='accumulated_time',
            field=models.FloatField(default=0.0, help_text='Total active time in seconds'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last user interaction', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, 'Question must be at least 10 characters'), django.core.validators.MaxLengthValidator(1000, 'Question must not exceed 1000 characters')]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Maximum number of attempts allowed', validators=[django.core.validators.MinValueValidator(1, 'Must allow at least 1 attempt'), django.core.validators.MaxValueValidator(100, 'Cannot exceed 100 attempts')]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes', null=True, validators=[django.core.validators.MinValueValidator(1, 'Time limit must be at least 1 minute'), django.core.validators.MaxValueValidator(1440, 'Time limit cannot exceed 24 hours')]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters')]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, 'Must have at least 1 question'), django.core.validators.MaxValueValidator(100, 'Cannot exceed 100 questions')]),
        ),
    ]
