# Generated by Django 5.2.6 on 2026-01-17 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizsession_accumulated_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reset_type', models.CharField(choices=[('specific', 'Specific User + Quiz'), ('all_students_one_quiz', 'All Students for One Quiz'), ('one_student_all_quizzes', 'One Student for All Quizzes'), ('all_students_all_quizzes', 'All Students for All Quizzes')], max_length=50)),
                ('sessions_deleted', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_received', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_reset_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
