# Generated by Django 5.2.6 on 2026-01-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizresetlog'),
        ('users', '0010_classroomquizassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='classroom_assignment',
            field=models.ForeignKey(blank=True, help_text='Link to classroom assignment if this is a classroom quiz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.classroomquizassignment'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='classroom_attempt_number',
            field=models.IntegerField(default=1, help_text='Attempt number for this classroom assignment'),
        ),
    ]
