# Generated by Django 5.2.6 on 2026-01-20 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quizsession_classroom_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generation_prompt', models.TextField(help_text='The prompt sent to the AI model')),
                ('model_used', models.CharField(help_text='AI model name (e.g., gpt-4o, gemini-pro)', max_length=50)),
                ('generation_metadata', models.JSONField(default=dict, help_text='Tokens used, cost, generation time, etc.')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether the teacher approved this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_questions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_metadata', to='quiz.question')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_generated_questions',
                'ordering': ['-created_at'],
            },
        ),
    ]
