# Generated by Django 5.2.6 on 2026-01-20 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_aigeneratedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='visibility',
            field=models.CharField(choices=[('global', 'Global - Show in overall dashboard'), ('classroom_only', 'Classroom Only - Only in assigned classrooms'), ('both', 'Both - Show everywhere')], default='global', help_text='Where this quiz should be visible to students', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='allow_retakes',
            field=models.BooleanField(default=False, help_text='Allow students to retake this quiz (global)'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Maximum attempts for global access', validators=[django.core.validators.MinValueValidator(1, 'Must allow at least 1 attempt'), django.core.validators.MaxValueValidator(100, 'Cannot exceed 100 attempts')]),
        ),
    ]
