# Generated by Django 5.2.6 on 2026-01-20 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_quiz_visibility_alter_quiz_allow_retakes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='auto_grade',
            field=models.BooleanField(default=True, help_text='Use AI for automatic grading of text answers'),
        ),
        migrations.AddField(
            model_name='question',
            name='max_words',
            field=models.IntegerField(blank=True, help_text='Maximum word count for text answer', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_words',
            field=models.IntegerField(blank=True, help_text='Minimum word count for text answer', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='model_answer',
            field=models.TextField(blank=True, help_text='Reference answer for grading text responses'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer (10-200 words)'), ('essay', 'Essay (50-1000 words)')], default='mcq', help_text='Type of question', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='required_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keywords to check in text answers'),
        ),
        migrations.AddField(
            model_name='response',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text='AI-generated feedback'),
        ),
        migrations.AddField(
            model_name='response',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='AI-generated score', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='final_score',
            field=models.FloatField(blank=True, help_text='Final score after review', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('ai_graded', 'AI Graded'), ('teacher_reviewed', 'Teacher Reviewed'), ('finalized', 'Finalized')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='response',
            name='keyword_matches',
            field=models.JSONField(blank=True, default=dict, help_text='Matched and missing keywords'),
        ),
        migrations.AddField(
            model_name='response',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='Semantic similarity to model answer', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='teacher_feedback',
            field=models.TextField(blank=True, help_text="Teacher's feedback"),
        ),
        migrations.AddField(
            model_name='response',
            name='teacher_score',
            field=models.FloatField(blank=True, help_text='Teacher-assigned score', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='text_answer',
            field=models.TextField(blank=True, help_text="Student's text response"),
        ),
        migrations.AddField(
            model_name='response',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.MinLengthValidator(1, 'Option cannot be empty')]),
        ),
        migrations.AlterField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='selected_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
