# Generated by Django 5.2.6 on 2026-01-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_question_auto_grade_question_max_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='total_fullscreen_violations',
            field=models.IntegerField(default=0, help_text='Total times user exited fullscreen'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='total_no_face_violations',
            field=models.IntegerField(default=0, help_text='Total times no face was detected'),
        ),
    ]
