# Generated by Django 5.2.6 on 2026-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quizsession_total_fullscreen_violations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='visibility',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_type',
            field=models.CharField(choices=[('mixed', 'Mixed / All Types'), ('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('essay', 'Essay')], default='mixed', help_text='Type of questions in this quiz', max_length=20),
        ),
    ]
