# Generated by Django 5.0.1 on 2026-02-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_aigeneratedquestion_confidence_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='hidden_from_parent',
        ),
    ]
