# Generated by Django 6.0.2 on 2026-02-11 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_flashcard_is_approved_flashcarddeck_is_published"),
        ("quiz", "0021_remove_quizsession_hidden_from_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="learning_module",
            field=models.ForeignKey(
                blank=True,
                help_text="The learning module this question was generated from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="learning.learningmodule",
            ),
        ),
    ]
