# Generated by Django 5.2.6 on 2026-02-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_remove_response_ai_feedback_remove_response_ai_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
