# Generated by Django 5.2.6 on 2026-02-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_response_ai_feedback_response_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
