# Generated by Django 6.0.2 on 2026-02-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0028_question_auto_grade_question_max_words_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="auto_grade",
        ),
        migrations.RemoveField(
            model_name="question",
            name="max_words",
        ),
        migrations.RemoveField(
            model_name="question",
            name="min_words",
        ),
        migrations.RemoveField(
            model_name="question",
            name="model_answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="required_keywords",
        ),
        migrations.RemoveField(
            model_name="response",
            name="ai_feedback",
        ),
        migrations.RemoveField(
            model_name="response",
            name="ai_score",
        ),
        migrations.RemoveField(
            model_name="response",
            name="final_score",
        ),
        migrations.RemoveField(
            model_name="response",
            name="grading_status",
        ),
        migrations.RemoveField(
            model_name="response",
            name="keyword_matches",
        ),
        migrations.RemoveField(
            model_name="response",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="response",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="response",
            name="similarity_score",
        ),
        migrations.RemoveField(
            model_name="response",
            name="teacher_feedback",
        ),
        migrations.RemoveField(
            model_name="response",
            name="teacher_score",
        ),
        migrations.RemoveField(
            model_name="response",
            name="text_answer",
        ),
        migrations.RemoveField(
            model_name="response",
            name="word_count",
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("mcq", "Multiple Choice")],
                default="mcq",
                help_text="Type of question",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="question_type",
            field=models.CharField(
                choices=[("mixed", "Mixed / All Types"), ("mcq", "Multiple Choice")],
                default="mixed",
                help_text="Type of questions in this quiz",
                max_length=20,
            ),
        ),
    ]
