"""URLs of the /api/v1 learning API. One entry per path; `methods` picks the view for the HTTP method."""
from django.urls import path

from core.http import methods
from learning import views_api as api, views_ext as ext

urlpatterns = [
    path("session", methods(GET=api.session_info)),
    path("me", methods(GET=api.me)),
    path("register", methods(POST=api.register)),
    path("login", methods(POST=api.login)),
    path("logout", methods(POST=api.logout)),
    path("subjects", methods(GET=api.list_subjects, POST=api.create_subject)),
    path("account", methods(GET=api.account)),
    path("dashboard", methods(GET=api.dashboard)),
    path("saved", methods(GET=api.saved_answers)),
    path("search", methods(GET=api.search_all)),
    path("career", methods(GET=api.career_list, POST=api.career_create)),
    path("analytics", methods(GET=ext.analytics_overview)),
    path("account/cloud", methods(PUT=api.set_cloud)),
    path("account/password", methods(POST=api.change_password)),
    path("account/export", methods(GET=api.export_data)),
    path("account/delete", methods(POST=api.delete_account)),
    path("account/email", methods(PUT=api.set_email, DELETE=api.remove_email)),
    path("account/weekly", methods(PUT=api.set_weekly)),
    path("account/academic", methods(PUT=api.set_academic)),
    path("account/profile", methods(PUT=api.set_profile)),
    path("jobs/active", methods(GET=api.active_jobs)),
    path("analytics/report.pdf", methods(GET=ext.analytics_report)),
    path("analytics/workbook.xlsx", methods(GET=ext.analytics_workbook)),
    path("system/status", methods(GET=ext.system_status)),
    path("system/reindex", methods(POST=ext.system_reindex)),
    path("auth/password/forgot", methods(POST=api.forgot_password)),
    path("auth/password/reset", methods(POST=api.reset_password)),
    path("account/email/verify", methods(POST=api.verify_email)),
    path("account/digest/send-now", methods(POST=api.send_digest_now)),
    path("analytics/tables/<str:name>", methods(GET=ext.analytics_table)),
    path("subjects/<str:subject_id>", methods(GET=api.get_subject, PATCH=api.update_subject, DELETE=api.delete_subject)),
    path("career/<str:goal_id>", methods(GET=api.career_get, DELETE=api.career_delete)),
    path("subjects/<str:subject_id>/level", methods(PUT=api.set_level)),
    path("subjects/<str:subject_id>/materials", methods(GET=api.list_materials, POST=api.upload_material)),
    path("subjects/<str:subject_id>/topics", methods(GET=api.list_topics)),
    path("subjects/<str:subject_id>/search", methods(GET=api.search)),
    path("subjects/<str:subject_id>/questions", methods(POST=api.ask, GET=api.list_questions)),
    path("subjects/<str:subject_id>/mcq", methods(GET=api.list_mcq)),
    path("subjects/<str:subject_id>/quiz", methods(GET=api.quiz_home)),
    path("subjects/<str:subject_id>/progress", methods(GET=api.progress)),
    path("subjects/<str:subject_id>/revision", methods(GET=api.revision)),
    path("subjects/<str:subject_id>/report", methods(GET=api.report)),
    path("subjects/<str:subject_id>/report.csv", methods(GET=api.report_csv)),
    path("subjects/<str:subject_id>/prerequisites", methods(POST=api.add_prereq)),
    path("subjects/<str:subject_id>/flashcards", methods(GET=api.flashcards)),
    path("subjects/<str:subject_id>/mcq.csv", methods(GET=api.mcq_csv)),
    path("subjects/<str:subject_id>/notes", methods(GET=api.list_notes, POST=api.create_note)),
    path("subjects/<str:subject_id>/roadmap", methods(GET=api.get_roadmap)),
    path("subjects/<str:subject_id>/outlook", methods(GET=api.outlook)),
    path("subjects/<str:subject_id>/whatif", methods(POST=api.what_if)),
    path("subjects/<str:subject_id>/self-check", methods(GET=api.get_self_check, PUT=api.put_self_check)),
    path("subjects/<str:subject_id>/twin", methods(GET=api.learner_twin)),
    path("subjects/<str:subject_id>/examples", methods(POST=api.make_example, GET=api.list_examples)),
    path("subjects/<str:subject_id>/report.pdf", methods(GET=ext.subject_report_pdf)),
    path("subjects/<str:subject_id>/report.xlsx", methods(GET=ext.subject_report_xlsx)),
    path("subjects/<str:subject_id>/agents", methods(GET=ext.agent_console)),
    path("subjects/<str:subject_id>/materials/url", methods(POST=api.add_web_page)),
    path("subjects/<str:subject_id>/mcq/jobs", methods(POST=api.create_mcq_job)),
    path("subjects/<str:subject_id>/quiz/attempts", methods(POST=api.quiz_start)),
    path("subjects/<str:subject_id>/notes/from-answers", methods(POST=api.notes_from_answers)),
    path("subjects/<str:subject_id>/roadmap/profile", methods(PUT=api.set_roadmap_profile)),
    path("subjects/<str:subject_id>/roadmap/coach", methods(POST=api.ask_coach)),
    path("subjects/<str:subject_id>/agents/run", methods(POST=ext.agent_run)),
    path("subjects/<str:subject_id>/notes/smart", methods(POST=ext.smart_notes)),
    path("subjects/<str:subject_id>/mcq/jobs/<str:job_id>", methods(GET=api.get_mcq_job)),
    path("subjects/<str:subject_id>/quiz/attempts/<str:attempt_id>", methods(GET=api.quiz_state)),
    path("subjects/<str:subject_id>/quiz/attempts/<str:attempt_id>/answer", methods(POST=api.quiz_answer)),
    path("subjects/<str:subject_id>/quiz/attempts/<str:attempt_id>/events", methods(POST=api.quiz_event)),
    path("subjects/<str:subject_id>/quiz/attempts/<str:attempt_id>/terminate", methods(POST=api.quiz_terminate)),
    path("subjects/<str:subject_id>/quiz/attempts/<str:attempt_id>/result", methods(GET=api.quiz_result)),
    path("subjects/<str:subject_id>/quiz/attempts/<str:attempt_id>/finish", methods(POST=api.quiz_finish)),
    path("subjects/<str:subject_id>/quiz/attempts/<str:attempt_id>/report.pdf", methods(GET=ext.attempt_report_pdf)),
    path("subjects/<str:subject_id>/materials/<str:document_id>", methods(GET=api.get_material, DELETE=api.delete_material)),
    path("subjects/<str:subject_id>/questions/<str:question_id>", methods(GET=api.get_question, DELETE=api.delete_question)),
    path("subjects/<str:subject_id>/mcq/<str:item_id>", methods(DELETE=api.delete_mcq)),
    path("subjects/<str:subject_id>/notes/<str:note_id>", methods(GET=api.get_note, PUT=api.update_note, DELETE=api.delete_note)),
    path("subjects/<str:subject_id>/questions/<str:question_id>/feedback", methods(POST=api.question_feedback)),
    path("subjects/<str:subject_id>/mcq/<str:item_id>/answer", methods(GET=api.mcq_answer)),
    path("subjects/<str:subject_id>/questions/<str:question_id>/saved", methods(PUT=api.save_question)),
    path("subjects/<str:subject_id>/flashcards/<str:item_id>/review", methods(POST=api.review_flashcard)),
    path("subjects/<str:subject_id>/materials/<str:document_id>/file", methods(GET=api.material_file)),
    path("subjects/<str:subject_id>/materials/<str:doc_id>/role", methods(PATCH=api.set_doc_role)),
    path("subjects/<str:subject_id>/prerequisites/<str:topic_id>/<str:prereq_id>", methods(DELETE=api.remove_prereq)),
]
