# Generated by Django 5.0.1 on 2026-09-05 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('diagnostic', 'Initial Diagnostic'), ('verification', 'Post-Intervention Verification'), ('pyq_practice', 'PYQ Practice')], default='diagnostic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=15)),
                ('score_pct', models.FloatField(default=0.0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('error_categories', models.JSONField(default=dict)),
                ('root_cause_analysis', models.TextField(blank=True, default='')),
                ('weak_subtopics', models.JSONField(default=list)),
                ('tab_switches', models.IntegerField(default=0)),
                ('integrity_terminated', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_diagnostic_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_answer', models.CharField(max_length=5)),
                ('explanation', models.TextField(blank=True, default='')),
                ('student_answer', models.CharField(blank=True, default='', max_length=5)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('difficulty_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('concept_tag', models.CharField(blank=True, default='', max_length=100)),
                ('question_type', models.CharField(default='mcq', max_length=30)),
                ('order_in_session', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluator_agent.diagnosticsession')),
            ],
            options={
                'db_table': 'nexus_diagnostic_questions',
                'ordering': ['order_in_session'],
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=200)),
                ('topic_name', models.CharField(max_length=200)),
                ('subtopics', models.JSONField(default=list)),
                ('lab_exercises', models.JSONField(default=list)),
                ('self_reported_pct', models.FloatField(default=0.0)),
                ('verified_pct', models.FloatField(default=0.0)),
                ('confidence_gap', models.FloatField(default=0.0)),
                ('mastery_trend', models.FloatField(default=0.0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('weak', 'Weak (< 50%)'), ('developing', 'Developing (50–79%)'), ('mastered', 'Mastered (≥ 80%)')], default='not_started', max_length=15)),
                ('failure_risk_pct', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to='syllabus.academicsubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_topic_masteries',
                'ordering': ['unit_name', 'topic_name'],
                'unique_together': {('user', 'subject', 'unit_name', 'topic_name')},
            },
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='topic_mastery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='evaluator_agent.topicmastery'),
        ),
    ]
