# Generated by Django 5.0.1 on 2026-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_classroomquizassignment_prerequisite_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='children',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_email',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('quiz_assigned', 'Quiz Assigned'), ('quiz_graded', 'Quiz Graded'), ('classroom_invite', 'Classroom Invitation'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10),
        ),
        migrations.DeleteModel(
            name='ParentStudentLink',
        ),
    ]
