# Generated by Django 5.0.1 on 2026-09-05 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('career_goal', models.CharField(blank=True, default='', max_length=200)),
                ('study_hours_per_day', models.FloatField(default=2.0)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_academic_profiles',
            },
        ),
    ]
