# Generated by Django 5.2.6 on 2026-01-14 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_parentstudentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='co_teachers',
            field=models.ManyToManyField(blank=True, related_name='co_teaching_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
