# Generated by Django 5.2.6 on 2026-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_classroom_co_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference_dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='preference_email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
