# Generated by Django 5.0.1 on 2026-02-10 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '__first__'),
        ('users', '0012_alter_classroom_id_alter_classroominvitation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomquizassignment',
            name='prerequisite_module',
            field=models.ForeignKey(blank=True, help_text='Student must complete this module before taking the quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_quizzes', to='learning.learningmodule'),
        ),
        migrations.AddField(
            model_name='classroomquizassignment',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, help_text='Time limit for this assignment', null=True),
        ),
    ]
