# Generated by Django 5.2.6 on 2026-02-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_classroomquizassignment_shuffle_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomquizassignment',
            name='shuffle_options',
            field=models.BooleanField(default=True, help_text='Randomize answer options for students'),
        ),
    ]
