# Generated by Django 6.0.6 on 2026-09-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(max_length=80)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('detail', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
