# Generated by Django 5.2.6 on 2026-01-19 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_classroomleaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learning_style', models.CharField(choices=[('visual', 'Visual Learner'), ('reading', 'Reading/Writing Learner'), ('problem_solving', 'Problem-Solving Learner'), ('explanation', 'Explanation-Based Learner')], default='visual', max_length=20)),
                ('preferred_study_time', models.CharField(blank=True, max_length=20, null=True)),
                ('initial_ability', models.FloatField(default=0.0, help_text='Initial theta value from diagnostic test (IRT)')),
                ('current_ability', models.FloatField(default=0.0, help_text='Current estimated ability (updated over time)')),
                ('learning_speed', models.FloatField(default=1.0, help_text='Relative learning speed (1.0 = average)')),
                ('guessing_tendency', models.FloatField(default=0.0, help_text='Probability of guessing (0-1)')),
                ('consistency_score', models.FloatField(default=0.5, help_text='Consistency in performance (0-1)')),
                ('avg_session_duration', models.IntegerField(default=0, help_text='Average study session in minutes')),
                ('total_study_time', models.IntegerField(default=0, help_text='Total study time in minutes')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasteryVector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concept_id', models.CharField(help_text='Reference to concept in knowledge graph', max_length=100)),
                ('mastery_score', models.FloatField(default=0.0, help_text='Current mastery level (0-1)')),
                ('attempts_count', models.IntegerField(default=0, help_text='Number of attempts on this concept')),
                ('correct_count', models.IntegerField(default=0, help_text='Number of correct attempts')),
                ('total_time_spent', models.IntegerField(default=0, help_text='Total time spent in seconds')),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('initial_score', models.FloatField(default=0.0, help_text='First attempt score')),
                ('peak_score', models.FloatField(default=0.0, help_text='Best score achieved')),
                ('recent_trend', models.FloatField(default=0.0, help_text='Recent improvement trend (-1 to 1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_vectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mastery_vectors',
                'ordering': ['-mastery_score'],
                'indexes': [models.Index(fields=['user', 'mastery_score'], name='mastery_vec_user_id_04c584_idx'), models.Index(fields=['concept_id'], name='mastery_vec_concept_d2fe26_idx')],
                'unique_together': {('user', 'concept_id')},
            },
        ),
        migrations.CreateModel(
            name='SubjectConfidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('science', 'Science'), ('english', 'English'), ('social_studies', 'Social Studies'), ('hindi', 'Hindi'), ('computer_science', 'Computer Science')], max_length=30)),
                ('confidence_level', models.IntegerField(default=3, help_text='1=Very Low, 2=Low, 3=Medium, 4=High, 5=Very High')),
                ('actual_performance', models.FloatField(blank=True, help_text='Actual measured performance (0-1)', null=True)),
                ('confidence_accuracy', models.FloatField(blank=True, help_text='How accurate is self-assessment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_confidences', to='users.learningprofile')),
            ],
            options={
                'db_table': 'subject_confidences',
                'ordering': ['subject'],
                'unique_together': {('profile', 'subject')},
            },
        ),
    ]
