# Generated by Django 5.2.6 on 2026-01-19 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_quizresetlog'),
        ('users', '0009_learningprofile_masteryvector_subjectconfidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomQuizAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('quiz_mode', models.CharField(choices=[('practice', 'Practice'), ('assessment', 'Assessment')], default='practice', max_length=20)),
                ('allow_unlimited_attempts', models.BooleanField(default=True, help_text='For practice mode')),
                ('show_immediate_feedback', models.BooleanField(default=True, help_text='For practice mode')),
                ('max_attempts', models.IntegerField(default=1, help_text='For assessment mode')),
                ('strict_time_limit', models.BooleanField(default=True, help_text='Enforce time limit strictly')),
                ('enable_proctoring', models.BooleanField(default=False, help_text='Enable proctoring features')),
                ('show_results_after_due', models.BooleanField(default=True, help_text='Show results only after due date')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_quizzes', to='users.classroom')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='quiz.quiz')),
            ],
            options={
                'db_table': 'classroom_quiz_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('classroom', 'quiz')},
            },
        ),
    ]
