# Generated by Django 5.0.1 on 2026-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_children_remove_user_parent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomquizassignment',
            name='shuffle_questions',
            field=models.BooleanField(default=True, help_text='Randomize question order for students'),
        ),
    ]
