# Generated by Django 5.0.1 on 2026-09-05 09:09

import django.db.models.deletion
import uuid
import workspace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectWorkspace',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('overall_verified_mastery', models.FloatField(default=0.0)),
                ('overall_self_mastery', models.FloatField(default=0.0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_study_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='syllabus.academicsubject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nexus_workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicFile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=workspace.models.workspace_file_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('notes', 'Lecture Notes'), ('pyq', 'Previous Year Questions'), ('lab', 'Lab Sheet / Practical'), ('assessment', 'Internal Assessment'), ('reference', 'Reference Material'), ('other', 'Other')], default='other', max_length=15)),
                ('file_size_kb', models.FloatField(default=0.0)),
                ('auto_unit', models.CharField(blank=True, default='', max_length=200)),
                ('auto_topic', models.CharField(blank=True, default='', max_length=200)),
                ('classification_confidence', models.FloatField(default=0.0)),
                ('classification_done', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('text_extracted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_files', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workspace.subjectworkspace')),
            ],
            options={
                'db_table': 'nexus_academic_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
